### ISSUE TITLE
Fails in Windows on import stage:  (_sqlite3: %1 is non Win32 application.)

### ISSUE THREAD

**Issue by far-rainbow** [Nekmo/proxy-db#11]
* proxy-db version: 0.2.4
* Python version: 3.8
* Operating System: Windows-7

### Description
File "C:\python38\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: %1 не является приложением Win32.
translation to English: (_sqlite3: %1 is non Win32 application.)
### What I Did

fails just on import stage
from proxy_db.proxies import ProxiesList

**Comment by Nekmo** [comment]
This seems like a error installing Python on Windows.

https://stackoverflow.com/questions/54876404/unable-to-import-sqlite3-using-anaconda-python

**Comment by Nekmo** [comment]
Closed due to inactivity.
