### ISSUE TITLE
Filtering by votes on ProxiesList

### ISSUE THREAD

**Issue by javi-aranda** [Nekmo/proxy-db#37]
Currently I believe `ProxiesList` only supports `provider`, `protocol`, `country` and `strategy` as arguments. It would be a nice feature filtering by minimum number of `votes`.

**Comment by javi-aranda** [comment]
Closing after seeing this was already implemented by passing `strategy=VotesListingStrategy(min_votes=<int>)`

**Comment by Nekmo** [comment]
Thanks for your report :)
